test v1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,4 +28,4 @@ jobs:
       run: |
         OUTPUT=$(python app.py)
         echo "$OUTPUT"
-        echo "$OUTPUT" | grep "Processing" || (echo "Expected output not found!" && exit 1)
+        echo "$OUTPUT" | grep "Found book" || (echo "Expected output not found!" && exit 1)
